// Données initiales et de secours réalistes pour les clubs i-motion EMS en Tunisie

export const INITIAL_USERS = [
  {
    id: 1,
    nom: 'Ben Salah',
    prenom: 'Youssef',
    email: 'admin@imotion.tn',
    motDePasse: 'admin123',
    role: 'ADMINISTRATEUR',
    dateInscrit: '2025-01-10T09:00:00Z',
  },
  {
    id: 2,
    nom: 'Trabelsi',
    prenom: 'Sarra',
    email: 'membre@imotion.tn',
    motDePasse: 'membre123',
    role: 'MEMBRE',
    dateInscrit: '2025-02-15T14:30:00Z',
  },
  {
    id: 3,
    nom: 'Gharbi',
    prenom: 'Karim',
    email: 'karim.g@gmail.com',
    motDePasse: 'karim123',
    role: 'MEMBRE',
    dateInscrit: '2025-03-01T11:15:00Z',
  },
  {
    id: 4,
    nom: 'Mansour',
    prenom: 'Ines',
    email: 'ines.m@yahoo.fr',
    motDePasse: 'ines123',
    role: 'MEMBRE',
    dateInscrit: '2025-03-12T16:45:00Z',
  }
];

export const INITIAL_COACHES = [
  {
    id: 1,
    nom: 'Ben Amor',
    prenom: 'Mehdi',
    specialite: 'Expert EMS Cardio & HIIT',
    experience: '6 ans d\'expérience',
    bio: 'Certifié i-motion Master Trainer, spécialiste du conditionnement métabolique et de la haute intensité.',
    avatar: 'MA',
    centreId: 1,
  },
  {
    id: 2,
    nom: 'Chaabane',
    prenom: 'Mariem',
    specialite: 'Coach EMS Posture & Santé du Dos',
    experience: '5 ans d\'expérience',
    bio: 'Kinésithérapeute du sport et instructrice EMS dédiée au réalignement vertébral et gainage profond.',
    avatar: 'MC',
    centreId: 1,
  },
  {
    id: 3,
    nom: 'Riahi',
    prenom: 'Slim',
    specialite: 'Sculpt & Musculation Profonde',
    experience: '7 ans d\'expérience',
    bio: 'Préparateur physique athlétique, expert en renforcement et hypertrophie par impulsions sans fil bio-sync.',
    avatar: 'SR',
    centreId: 2,
  },
  {
    id: 4,
    nom: 'Trabelsi',
    prenom: 'Amina',
    specialite: 'Drainage & Tonification Minceur',
    experience: '4 ans d\'expérience',
    bio: 'Instructrice certifiée en électromassage lymphatique et protocoles fessiers/abdos ciblés.',
    avatar: 'AT',
    centreId: 2,
  },
  {
    id: 5,
    nom: 'Karray',
    prenom: 'Yassine',
    specialite: 'Performance Sportive & Récupération',
    experience: '8 ans d\'expérience',
    bio: 'Coach sportif d\'élite, spécialiste de l\'explosivité et de la décharge musculaire post-effort.',
    avatar: 'YK',
    centreId: 4,
  },
  {
    id: 6,
    nom: 'Dridi',
    prenom: 'Nour',
    specialite: 'Bien-être & Remise en Forme EMS',
    experience: '3 ans d\'expérience',
    bio: 'Accompagnement bienveillant et progressif pour la reprise d\'activité et la tonification globale.',
    avatar: 'ND',
    centreId: 3,
  }
];

export const INITIAL_CENTRES = [
  {
    id: 1,
    nom: 'i-motion Club - Les Berges du Lac 2',
    description: 'Centre premium d\'électrostimulation sans fil nouvelle génération i-motion v2. Équipements de pointe, vestiaires individuels de luxe et coaching personnalisé par des instructeurs certifiés.',
    adresse: 'Rue de la Feuille d\'Érable, Les Berges du Lac 2, Tunis 1053',
    numTel: '+216 71 860 120',
    ville: 'Tunis',
  },
  {
    id: 2,
    nom: 'i-motion Club - Ennasr 2',
    description: 'Le premier studio EMS d\'Ennasr offrant des sessions de 20 minutes équivalentes à 4 heures de musculation intensive. Espace high-tech climatisé et programmes personnalisés.',
    adresse: 'Avenue Hédi Nouira, Résidence Les Palmiers, Ennasr 2, Ariana 2037',
    numTel: '+216 70 820 440',
    ville: 'Ariana / Tunis',
  },
  {
    id: 3,
    nom: 'i-motion Club - La Marsa',
    description: 'Studio exclusif en bord de mer dédié à la tonification, au drainage lymphatique et à la perte de masse grasse par technologie EMS sans fil bio-sync.',
    adresse: 'Avenue Habib Bourguiba, La Marsa, Tunis 2070',
    numTel: '+216 71 740 330',
    ville: 'La Marsa',
  },
  {
    id: 4,
    nom: 'i-motion Club - Sousse Kantaoui',
    description: 'Centre moderne situé au cœur de la zone touristique de Sousse. Prise en charge individualisée, réhabilitation posturale et programmes minceur express.',
    adresse: 'Boulevard du 14 Janvier, Port El Kantaoui, Sousse 4089',
    numTel: '+216 73 240 550',
    ville: 'Sousse',
  },
  {
    id: 5,
    nom: 'i-motion Club - Sfax Route de Téniour',
    description: 'Grand centre EMS spacieux avec 4 stations sans fil i-motion, suivi biométrique et programmes spécifiques pour sportifs et rééducation.',
    adresse: 'Route de Téniour Km 2, Sfax 3002',
    numTel: '+216 74 450 670',
    ville: 'Sfax',
  }
];

export const INITIAL_SEANCES = [
  {
    id: 1,
    nom: 'EMS Full Body Sculpt & Strength',
    description: 'Stimulation simultanée de plus de 300 muscles en 20 minutes chrono. Renforcement musculaire profond, gainage intense et galbe corporel.',
    type: 'Renforcement & Musculation',
    centreId: 1,
    coachIds: [1, 2, 3],
    moyenneNote: 4.8,
  },
  {
    id: 2,
    nom: 'EMS Cardio Burn & Metabolic Booster',
    description: 'Séance dynamique combinant impulsions EMS haute fréquence et exercices cardio fractionnés (HIIT). Brûle jusqu\'à 1500 kcal en post-combustion.',
    type: 'Cardio & Perte de Poids',
    centreId: 1,
    coachIds: [1, 3],
    moyenneNote: 4.9,
  },
  {
    id: 3,
    nom: 'EMS Dos Santé & Réalignement Postural',
    description: 'Programme ciblé pour soulager les lombalgies chroniques, renforcer les muscles érecteurs du rachis et redresser la colonne vertébrale sans charge articulaire.',
    type: 'Santé & Rééducation',
    centreId: 2,
    coachIds: [2],
    moyenneNote: 4.7,
  },
  {
    id: 4,
    nom: 'EMS Fessiers & Abdominaux Flash',
    description: 'Séance hyper-ciblée sur la sangle abdominale profonde (transverse), la taille et les fessiers. Résultats visibles dès 4 séances.',
    type: 'Tonification Ciblée',
    centreId: 2,
    coachIds: [3, 4],
    moyenneNote: 4.6,
  },
  {
    id: 5,
    nom: 'EMS Anti-Cellulite & Drainage Lymphatique',
    description: 'Fréquences douces d\'électromassage améliorant la micro-circulation sanguine, lissant la peau d\'orange et éliminant la rétention d\'eau.',
    type: 'Bien-être & Minceur',
    centreId: 3,
    coachIds: [4, 6],
    moyenneNote: 4.9,
  },
  {
    id: 6,
    nom: 'EMS Performance Athlétique',
    description: 'Optimisation de la force explosive, de la détente verticale et de l\'endurance anaérobie pour les athlètes et passionnés de fitness.',
    type: 'Performance Sportive',
    centreId: 4,
    coachIds: [1, 5],
    moyenneNote: 4.5,
  },
  {
    id: 7,
    nom: 'EMS Récupération Active & Relaxation',
    description: 'Programme de décharge musculaire par électrostimulation décontracturante pour éliminer les toxines et courbatures après un effort intense.',
    type: 'Récupération',
    centreId: 5,
    coachIds: [5, 6],
    moyenneNote: 4.8,
  }
];

export const INITIAL_AVIS = [
  {
    id: 1,
    note: 5,
    noteCoach: 5,
    commentaire: 'Séance impressionnante au Lac 2 ! En seulement 20 minutes, j\'ai ressenti un travail musculaire bien supérieur à 1h30 de musculation classique. Coach très attentif et matériel impeccable.',
    dateCreation: '2025-03-02T10:30:00Z',
    seanceId: 1,
    utilisateurId: 2,
    utilisateurNom: 'Sarra Trabelsi',
    coachId: 1,
    coachNom: 'Mehdi Ben Amor',
  },
  {
    id: 2,
    note: 5,
    noteCoach: 5,
    commentaire: 'Le Cardio Burn est redoutable mais incroyablement efficace ! Après 6 séances, j\'ai perdu 3 cm de tour de taille. Superbe ambiance et vestiaires nickel.',
    dateCreation: '2025-03-05T17:15:00Z',
    seanceId: 2,
    utilisateurId: 3,
    utilisateurNom: 'Karim Gharbi',
    coachId: 1,
    coachNom: 'Mehdi Ben Amor',
  },
  {
    id: 3,
    note: 4,
    noteCoach: 5,
    commentaire: 'Excellent travail sur les muscles dorsaux. J\'avais des douleurs au bas du dos qui ont pratiquement disparu après 4 semaines. Je recommande vivement le centre Ennasr.',
    dateCreation: '2025-03-08T11:00:00Z',
    seanceId: 3,
    utilisateurId: 4,
    utilisateurNom: 'Ines Mansour',
    coachId: 2,
    coachNom: 'Mariem Chaabane',
  },
  {
    id: 4,
    note: 5,
    noteCoach: 4,
    commentaire: 'Une technologie sans fil au top, pas de câbles encombrants, on bouge en toute liberté. Les impulsions sont réglées sur mesure par le coach.',
    dateCreation: '2025-03-10T14:20:00Z',
    seanceId: 1,
    utilisateurId: 3,
    utilisateurNom: 'Karim Gharbi',
    coachId: 3,
    coachNom: 'Slim Riahi',
  },
  {
    id: 5,
    note: 5,
    noteCoach: 5,
    commentaire: 'Programme anti-cellulite testé à La Marsa : effet drainant immédiat, jambes légères dès la première séance. Accueil très chaleureux.',
    dateCreation: '2025-03-12T09:45:00Z',
    seanceId: 5,
    utilisateurId: 2,
    utilisateurNom: 'Sarra Trabelsi',
    coachId: 4,
    coachNom: 'Amina Trabelsi',
  },
  {
    id: 6,
    note: 4,
    noteCoach: 4,
    commentaire: 'Très bonne intensité sur les fessiers et abdos. Courbatures intenses garanties le lendemain mais les résultats sont là !',
    dateCreation: '2025-03-14T16:00:00Z',
    seanceId: 4,
    utilisateurId: 4,
    utilisateurNom: 'Ines Mansour',
    coachId: 4,
    coachNom: 'Amina Trabelsi',
  },
  {
    id: 7,
    note: 5,
    noteCoach: 5,
    commentaire: 'Le centre de Sousse est moderne et le coach maîtrise parfaitement les réglages i-motion. Super séance de récupération.',
    dateCreation: '2025-03-15T18:30:00Z',
    seanceId: 7,
    utilisateurId: 2,
    utilisateurNom: 'Sarra Trabelsi',
    coachId: 5,
    coachNom: 'Yassine Karray',
  }
];
